# Generated by Django 5.0.7 on 2024-07-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgdata',
            name='img',
            field=models.ImageField(upload_to='media/myImg'),
        ),
    ]
