# Generated by Django 5.0.7 on 2024-07-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_imgdata_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgdata',
            name='img',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
